"""Generated by ``zerobox recipe add sqlite`` for server-only Python code.

Uses SQLModel for shared FastAPI validation and table metadata while compiling
its SQLAlchemy statements for a sessionless HTTP bridge. Each request sends one
statement. Re-run the recipe into a new path to compare future updates; never
expose this module or its injected configuration to browser-delivered code.
"""

from __future__ import annotations

import math
import os
import re
from collections.abc import Sequence
from typing import Literal, TypeVar, Union

import httpx
from sqlalchemy import Table
from sqlalchemy.dialects import sqlite
from sqlalchemy.schema import CreateTable
from sqlalchemy.sql import Executable
from sqlmodel import SQLModel

SQLiteParameter = Union[str, int, float, bool, None]
SQLiteMethod = Literal["run", "all", "get", "values"]
SQLiteModel = TypeVar("SQLiteModel", bound=SQLModel)
SQLITE_DIALECT = sqlite.dialect(paramstyle="qmark")
MAX_SAFE_INTEGER = 9_007_199_254_740_991
_ERROR_CODE = re.compile(r"^[a-z][a-z0-9_]{0,63}$")
_ERROR_MESSAGES = {
    "unknown_body_key": "SQLite request was rejected",
    "invalid_request": "SQLite request was rejected",
    "query_error": "SQLite query failed",
    "unresolvable_app_identity": "SQLite app identity could not be verified",
    "integration_not_enabled": "SQLite integration is not enabled",
    "unknown_sqlite_endpoint": "SQLite endpoint was not found",
    "identity_lookup_failed": "SQLite app identity is unavailable",
    "backend_unavailable": "SQLite backend is unavailable",
    "settings_unavailable": "SQLite app settings are unavailable",
    "sqlite_not_configured": "SQLite is not configured on this control plane",
    "bridge_unavailable": "SQLite bridge is unavailable",
}
_SAFE_FAILURES = {
    "unknown_body_key": ({400}, 400, "SQLite request was rejected"),
    "invalid_request": ({400}, 400, "SQLite request was rejected"),
    "query_error": ({400}, 400, "SQLite query failed"),
    "unresolvable_app_identity": ({400, 403}, 403, "SQLite app identity could not be verified"),
    "integration_not_enabled": ({403}, 403, "SQLite integration is not enabled"),
    "unknown_sqlite_endpoint": ({404}, 404, "SQLite endpoint was not found"),
    "identity_lookup_failed": ({502}, 502, "SQLite app identity is unavailable"),
    "backend_unavailable": ({502}, 502, "SQLite backend is unavailable"),
    "settings_unavailable": ({503}, 503, "SQLite app settings are unavailable"),
    "sqlite_not_configured": ({503}, 503, "SQLite is not configured on this control plane"),
    "bridge_unavailable": ({503}, 503, "SQLite bridge is unavailable"),
}


class SQLiteBridgeError(RuntimeError):
    """Credential-safe bridge failure with a validated stable code."""

    def __init__(self, status_code: int, message: str, code: str = "bridge_error") -> None:
        super().__init__(message)
        self.status_code = status_code
        self.code = code


def safe_bridge_failure(error: SQLiteBridgeError) -> tuple[int, dict[str, str]]:
    """Map a bridge failure to a fixed response; never return ``str(error)``."""

    failure = _SAFE_FAILURES.get(error.code)
    if failure is None:
        return 500, {"error": "Internal server error", "code": "bridge_error"}
    allowed_statuses, fallback_status, message = failure
    status = error.status_code if error.status_code in allowed_statuses else fallback_status
    return status, {"error": message, "code": error.code}


def _json_parameter(value: object) -> SQLiteParameter:
    if value is None or isinstance(value, (str, bool)):
        return value
    if isinstance(value, int):
        if not -MAX_SAFE_INTEGER <= value <= MAX_SAFE_INTEGER:
            raise ValueError(
                f"SQLite integer parameters must be between "
                f"{-MAX_SAFE_INTEGER} and {MAX_SAFE_INTEGER}"
            )
        return value
    if isinstance(value, float) and math.isfinite(value):
        return value
    raise TypeError(f"SQLite parameter is not JSON-safe: {type(value).__name__}")


def _compile(statement: Executable) -> tuple[str, list[SQLiteParameter]]:
    compiled = statement.compile(
        dialect=SQLITE_DIALECT,
        compile_kwargs={"render_postcompile": True},
    )
    positions = getattr(compiled, "positiontup", None)
    if positions is None:
        raise TypeError("Expected a parameterized SQLite statement")
    return str(compiled), [_json_parameter(compiled.params[name]) for name in positions]


def _model_table(model: type[SQLiteModel]) -> Table:
    table = getattr(model, "__table__", None)
    if not isinstance(table, Table):
        raise TypeError("SQLite models must declare table=True")
    return table


class ZeroboxSQLite:
    """Synchronous SQLModel transport for normal ``def`` FastAPI handlers."""

    def __init__(self) -> None:
        base_url = os.environ.get("ZEROBOX_SQLITE_URL", "").strip().rstrip("/")
        token = os.environ.get("ZEROBOX_APP_TOKEN", "").strip()
        if not base_url or not token:
            raise RuntimeError("Enable SQLite and run this code inside the ZeroBox runner")
        self._query_url = f"{base_url}/query"
        self._headers = {"X-Zerobox-App-Token": token}
        # HTTPX applies this independently to connect/read/write/pool phases;
        # it is not a ten-second end-to-end deadline.
        self._http = httpx.Client(timeout=10.0)

    def _query(
        self,
        sql: str,
        params: Sequence[SQLiteParameter],
        method: SQLiteMethod,
    ) -> list[list[object]]:
        try:
            response = self._http.post(
                self._query_url,
                headers=self._headers,
                json={"sql": sql, "params": list(params), "method": method},
            )
        except httpx.HTTPError:
            raise SQLiteBridgeError(
                503,
                "SQLite bridge request failed before receiving a response",
                "bridge_unavailable",
            ) from None

        try:
            body = response.json()
        except ValueError:
            if response.status_code == 502:
                raise SQLiteBridgeError(
                    503, "SQLite bridge is unavailable", "bridge_unavailable"
                ) from None
            raise SQLiteBridgeError(
                response.status_code, "SQLite endpoint returned invalid JSON"
            ) from None

        if not response.is_success:
            raw_code = body.get("code") if isinstance(body, dict) else None
            if raw_code is None and response.status_code == 502:
                raise SQLiteBridgeError(
                    503, "SQLite bridge is unavailable", "bridge_unavailable"
                )
            code = (
                raw_code
                if isinstance(raw_code, str) and _ERROR_CODE.fullmatch(raw_code)
                else "bridge_error"
            )
            raise SQLiteBridgeError(
                response.status_code,
                _ERROR_MESSAGES.get(code, f"SQLite request failed ({response.status_code})"),
                code,
            )

        rows = body.get("rows") if isinstance(body, dict) else None
        if not isinstance(rows, list) or not all(isinstance(row, list) for row in rows):
            raise SQLiteBridgeError(response.status_code, "SQLite endpoint returned invalid rows")
        return rows

    def run(self, statement: Executable) -> None:
        sql, params = _compile(statement)
        self._query(sql, params, "run")

    def fetch_all(self, statement: Executable) -> list[list[object]]:
        """Return validated raw rows for projections that are not full models."""

        sql, params = _compile(statement)
        return self._query(sql, params, "all")

    def fetch_models(
        self,
        statement: Executable,
        model: type[SQLiteModel],
    ) -> list[SQLiteModel]:
        """Execute ``select(Model)`` and validate every row as that SQLModel."""

        table = _model_table(model)
        expected_keys = [column.key for column in table.columns]
        selected_columns = getattr(statement, "selected_columns", None)
        selected_keys = list(selected_columns.keys()) if selected_columns is not None else []
        if selected_keys != expected_keys:
            raise TypeError("fetch_models requires a full select(Model) statement")

        models: list[SQLiteModel] = []
        for row in self.fetch_all(statement):
            if len(row) != len(expected_keys):
                raise SQLiteBridgeError(500, "SQLite endpoint returned invalid model rows")
            models.append(model.model_validate(dict(zip(expected_keys, row))))
        return models

    def fetch_model(
        self,
        statement: Executable,
        model: type[SQLiteModel],
    ) -> SQLiteModel | None:
        """Fetch at most two rows, then validate that zero or one model exists."""

        limit = getattr(statement, "limit", None)
        if not callable(limit):
            raise TypeError("fetch_model requires a select(Model) statement")
        models = self.fetch_models(limit(2), model)
        if len(models) > 1:
            raise TypeError("fetch_model requires a query bounded to one row")
        return models[0] if models else None

    def create_table(self, model: type[SQLiteModel]) -> None:
        """Create a ``table=True`` SQLModel idempotently with compiled DDL."""

        table = _model_table(model)
        ddl = str(CreateTable(table, if_not_exists=True).compile(dialect=SQLITE_DIALECT))
        self.run_ddl(ddl)

    def run_ddl(self, sql: str) -> None:
        """Execute constant, reviewed schema DDL without parameters."""

        self._query(sql, (), "run")

    def close(self) -> None:
        self._http.close()
